CREATE TABLE webhook_events (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL UNIQUE,
    payload LONGTEXT,
    status VARCHAR(20),
    received_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
